version: "3.3"

services:

  db:
    # Crear base de datos de tipo Postgres.
    image: postgres:13.2
    volumes:
      # Enlazar el contenido de dentro del contenedor con el directorio en nuestra PC
      - ./database:/var/lib/postgresql/data
    environment:
      # Postgres usuario por variables de entorno
      POSTGRES_DB: marvel_db
      POSTGRES_USER: inove_user
      POSTGRES_PASSWORD: 123Marvel!

    ports:
      # Puerto en el que trabaja Postgres por defecto
      - 5432:5432

  adminer:
    # Interfaz para monitoreo y gestión de nuestra base de datos.
    image: adminer:4.8.0
    ports:
      - 8080:8080
    # Variables de entorno
    environment:
      DB_ENGINE: POSTGRES
    # Depende de que primero inicie "db"
    depends_on: ["db"]

  modulo_2:

    build:
      context: .
      dockerfile: dockerfile
    image: modulo_2
    container_name: modulo_2

    volumes:
      - type: bind
        source: .
        target: /opt/back_end
    ports:
        - "8000:8000"

    # Control de consola:
    stdin_open: true
    tty: true
    #command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
